### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Manipulador_IA)
add_subdirectory(Manipulador_IAContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Manipulador_IAplugin
    Manipulador_IAContentplugin
    QtQuickDesignerComponents)